export const GET_ALL_CHARACTERS_SUCCESS = 'GET_ALL_CHARACTERS_SUCCESS';
export const GET_ALL_CHARACTERS_ERROR = 'GET_ALL_CHARACTERS_ERROR';
export const CLEAR_ALL_CHARACTERS_ERROR = 'CLEAR_ALL_CHARACTERS_ERROR';
export const CLEAR_ALL_CHARACTERS = 'CLEAR_ALL_CHARACTERS';

export const GET_ONE_CHARACTER_SUCCESS = 'GET_ONE_CHARACTER_SUCCESS';
export const GET_ONE_CHARACTER_ERROR = 'GET_ONE_CHARACTER_ERROR';
export const CLEAR_ONE_CHARACTER_ERROR = 'CLEAR_ONE_CHARACTER_ERROR';
export const CLEAR_ONE_CHARACTER = 'CLEAR_ONE_CHARACTER';